title: Sleep Apnea Monitor

theme: jekyll-theme-hacker

github:
  repository_url: https://github.com/SAM-TCC

permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num